// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCscgt90NiAZcFB2YHV4lodyWD9qLGuxz0',
    appId: '1:331526088547:web:1fcfe6afe79d506cc49556',
    messagingSenderId: '331526088547',
    projectId: 'educampus-7777',
    authDomain: 'educampus-7777.firebaseapp.com',
    storageBucket: 'educampus-7777.firebasestorage.app',
    measurementId: 'G-11FQBGJV9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzyW7bb1OU2TIhsaDPnpVWZ8lT64eRcfQ',
    appId: '1:331526088547:android:2c00519f9146d867c49556',
    messagingSenderId: '331526088547',
    projectId: 'educampus-7777',
    storageBucket: 'educampus-7777.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfM_oLRBBWobwBaHhl8ght3uP7fVli1dw',
    appId: '1:331526088547:ios:606449ca9123e79dc49556',
    messagingSenderId: '331526088547',
    projectId: 'educampus-7777',
    storageBucket: 'educampus-7777.firebasestorage.app',
    iosBundleId: 'com.example.educampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfM_oLRBBWobwBaHhl8ght3uP7fVli1dw',
    appId: '1:331526088547:ios:606449ca9123e79dc49556',
    messagingSenderId: '331526088547',
    projectId: 'educampus-7777',
    storageBucket: 'educampus-7777.firebasestorage.app',
    iosBundleId: 'com.example.educampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCscgt90NiAZcFB2YHV4lodyWD9qLGuxz0',
    appId: '1:331526088547:web:8e2fe1ed4e3aab72c49556',
    messagingSenderId: '331526088547',
    projectId: 'educampus-7777',
    authDomain: 'educampus-7777.firebaseapp.com',
    storageBucket: 'educampus-7777.firebasestorage.app',
    measurementId: 'G-Y22F5WR0MK',
  );
}
